spring.application.name=bhaang
spring.datasource.url=jdbc:postgresql://localhost:5432/insurance_db
spring.datasource.username=athul
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# Spring AI OpenRouter Configuration
spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://openrouter.ai/api
spring.ai.openai.chat.options.model=stepfun/step-3.5-flash:free
# Add these lines
logging.level.org.springframework.web.client=DEBUG
logging.level.com.athul.bhaang=INFO
spring.ai.openai.chat.options.temperature=0.0
# Logging
logging.level.org.springframework.ai=DEBUG



springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui/index.html

server.error.include-message=always
server.error.include-stacktrace=always


spring.ai.vectorstore.chroma.client.host=http://localhost
spring.ai.vectorstore.chroma.client.port=8000

# 2. Collection Settings
spring.ai.vectorstore.chroma.collection-name=policies
spring.ai.vectorstore.chroma.initialize-schema=true

security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
# 1h in millisecond
security.jwt.expiration-time=3600000

# Root logging level
logging.level.root=INFO